
default: Getränkeautomat

Getränkeautomat.o: Getränkeautomat.c
	gcc -c Getränkeautomat.c -o Getränkeautomat.o

Getränkeautomat: Getränkeautomat.o
	gcc Getränkeautomat.o -o Getränkeautomat

clean:
	-rm -f Getränkeautomat.o
	-rm -f Getränkeautomat
