
default: MultiRechner

MultiRechner.o: MultiRechner.c
	gcc -c MultiRechner.c -o MultiRechner.o

MultiRechner: MultiRechner.o
	gcc MultiRechner.o -o MultiRechner

clean:
	-rm -f MultiRechner.o
	-rm -f MultiRechner
