
default: Flächeninhalt

Flächeninhalt.o: Flächeninhalt.c
	gcc -c Flächeninhalt.c -o Flächeninhalt.o

Flächeninhalt: Flächeninhalt.o
	gcc Flächeninhalt.o -o Flächeninhalt

clean:
	-rm -f Flächeninhalt.o
	-rm -f Flächeninhalt
