
default: Zahlenvergleich

Zahlenvergleich.o: Zahlenvergleich.c
	gcc -c Zahlenvergleich.c -o Zahlenvergleich.o

Zahlenvergleich: Zahlenvergleich.o
	gcc Zahlenvergleich.o -o Zahlenvergleich

clean:
	-rm -f Zahlenvergleich.o
	-rm -f Zahlenvergleich
