
default: S-M-S-Rechner

S-M-S-Rechner.o: S-M-S-Rechner.c
	gcc -c S-M-S-Rechner.c -o S-M-S-Rechner.o

S-M-S-Rechner: S-M-S-Rechner.o
	gcc S-M-S-Rechner.o -o S-M-S-Rechner

clean:
	-rm -f S-M-S-Rechner.o
	-rm -f S-M-S-Rechner
