
default: Notendurchschnitt

Notendurchschnitt.o: Notendurchschnitt.c
	gcc -c Notendurchschnitt.c -o Notendurchschnitt.o

Notendurchschnitt: Notendurchschnitt.o
	gcc Notendurchschnitt.o -o Notendurchschnitt

clean:
	-rm -f Notendurchschnitt.o
	-rm -f Notendurchschnitt
