
default: Zahlenausgabe

Zahlenausgabe.o: Zahlenausgabe.c
	gcc -c Zahlenausgabe.c -o Zahlenausgabe.o

Zahlenausgabe: Zahlenausgabe.o
	gcc Zahlenausgabe.o -o Zahlenausgabe

clean:
	-rm -f Zahlenausgabe.o
	-rm -f Zahlenausgabe
