
default: Sekundenrechner

Sekundenrechner.o: Sekundenrechner.c
	gcc -c Sekundenrechner.c -o Sekundenrechner.o

Sekundenrechner: Sekundenrechner.o
	gcc Sekundenrechner.o -o Sekundenrechner

clean:
	-rm -f Sekundenrechner.o
	-rm -f Sekundenrechner
